### PR TITLE
A draft README

### PR DESCRIPTION
**Pull request by Martin521**
Just a draft, please review / comment.

(For the implicitly proposed tools and repo structure, see our [temp repo](https://github.com/amplifying-fsharp/fsharplang/))

### CODE REVIEW

**Review by dawedawe — APPROVED** [review]

**Comment by vzarytovskii** [comment]
I think it's reasonable description, we can tweak it as we go if we find it not working. I'm happy to merge it @edgarfgp @Martin521 let me know if you're happy with it.

**Review by edgarfgp — APPROVED** [review]

**Comment by edgarfgp** [comment]
> I think it's reasonable description, we can tweak it as we go if we find it not working. I'm happy to merge it @edgarfgp @Martin521 let me know if you're happy with it.

LGTM

**Comment by Martin521** [comment]
> I think it's reasonable description, we can tweak it as we go if we find it not working. I'm happy to merge it @edgarfgp @Martin521 let me know if you're happy with it.

Yes, please merge it

**Comment by edgarfgp** [comment]
Will merge this. So we can make some progress here :)

**Pull request merged**
